name: Publish Docker image

env:
  CONFIG_REPO_NAME: flask-app

on:
  push:
    branches: [ "main" ]
jobs:

  image-push:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build --tag faozil/pythonflaskapp:${{ github.sha }} .

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: faozil/pythonflaskapp:${{ github.sha }}

  Update-Config-Repo:
    runs-on: ubuntu-latest
    needs: image-push
    steps:
      - run: |
          echo "promoting into dev environment!"
          git config --global user.email actions@github.com && git config --global user.name GitHub Actions
          echo "cloning config repo $CONFIG_REPO_NAME"
          git clone https://oauth2:${{ secrets.WORK_TOKEN }}@github.com/${{ github.repository_owner }}/$CONFIG_REPO_NAME.git
          cd $CONFIG_REPO_NAME
          echo "checkout main branch"
          git checkout main
          git add . && git commit -m "Updated Image tag to ${{ github.sha }}"
          git push
